Check for avformat_alloc_context() and use when available.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9457,6 +9457,72 @@ else
 echo "${ECHO_T}yes" >&6; }
 	:
 fi
+    { echo "$as_me:$LINENO: checking for avformat_alloc_context in -llibavformat" >&5
+echo $ECHO_N "checking for avformat_alloc_context in -llibavformat... $ECHO_C" >&6; }
+if test "${ac_cv_lib_libavformat_avformat_alloc_context+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llibavformat  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char avformat_alloc_context ();
+int
+main ()
+{
+return avformat_alloc_context ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_libavformat_avformat_alloc_context=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_libavformat_avformat_alloc_context=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_libavformat_avformat_alloc_context" >&5
+echo "${ECHO_T}$ac_cv_lib_libavformat_avformat_alloc_context" >&6; }
+if test $ac_cv_lib_libavformat_avformat_alloc_context = yes; then
+  FFMPEG_CFLAGS="-DHAS_AVFORMAT_ALLOC_CONTEXT $FFMPEG_CFLAGS"
+fi
+
+
     CFLAGS="$CFLAGS -DHAVE_FFMPEG $FFMPEG_CFLAGS"
     CPPFLAGS="$CPPFLAGS -DHAVE_FFMPEG $FFMPEG_CFLAGS"
     LIBS="$LIBS $FFMPEG_LIBS"
